New dribbler
RoboTeamTwente/roboteam_microcontroller6.0 pull request #18
Opened 2024-05-28 08:06 UTC by DarioC02

2024-05-28 11:38 UTC, JWillegers requested changes
see comments

2024-05-28 11:38 UTC, JWillegers commented on Core/Inc/dribbler_board/Util/AC_DC_util.h
Change CUR_DRIBBLER to CURRENT_DRIBBLER and VOLT_DRIBBLER to VOLTAGE_DRIBBLER

2024-05-28 11:38 UTC, JWillegers commented on Core/Inc/dribbler_board/peripherals/dribbler.h
> +#define CURRENT_THRESHOLD 600
please add documentation either here or on the wiki why this is the treshold

2024-05-28 11:38 UTC, JWillegers commented on Core/Src/dribbler_board/Util/AC_DC_util.c
remove file, is unneccesary

2024-05-28 11:38 UTC, JWillegers commented on Core/Src/dribbler_board/dribbler_board.c
please clean up file, remove empty functions and delete old, commented out code

2024-05-28 11:38 UTC, JWillegers commented on Core/Src/dribbler_board/peripherals/ballSensor.c
could you add a test in ballsensor_init() to see if ball sensor is working?

2024-05-30 11:28 UTC, jggithub17 approved these changes
Reviewed the last three commits, the commits before that were approved by Jonathan

2024-05-30 11:30 UTC, JWillegers approved these changes

2024-05-30 11:30 UTC, merged